AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Sample SAM Template for HelloWorld

  '
Globals:
  Function:
    Timeout: 10
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://c3abc765-ee01-447d-b78a-14bc2613bf72/fa422a9cfc96fb817f38058b4686eed2
      Handler: HelloWorld::HelloWorld.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SNS
            SqsSubscription: false
            FilterPolicy:
              schema:
              - block
  SNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: consumer-01
